# Generated by Django 5.1.1 on 2024-10-17 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(unique=True)),
                ('value', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'attributes',
            },
        ),
    ]
