# Generated by Django 5.1.1 on 2024-10-17 00:21

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(unique=True)),
                ('shortDescription', models.CharField()),
                ('longDescription1', models.CharField()),
                ('longDescription2', models.CharField()),
                ('longDescription3', models.CharField()),
                ('longDescription4', models.CharField(blank=True)),
                ('longDescription5', models.CharField(blank=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
